--- #YAML:1.0
name: OpenFrame-Segment-Apache
version: 1.10
license: perl
distribution_type: module
requires:
  Apache: 1.27
  HTTP::Cookies: 1.25
  LWP::UserAgent: 2.001
  OpenFrame::AppKit: 3.03
  Test::More: 0.01
  URI: 1.21
recommends: {}
build_requires: {}
conflicts: {}
provides:
  OpenFrame::Example::ApacheSimple:
    file: lib/OpenFrame/Example/ApacheSimple.pm
    version: 1.02
  OpenFrame::Example::Redirector:
    file: lib/OpenFrame/Example/Redirector.pm
  OpenFrame::Segment::Apache:
    file: lib/OpenFrame/Segment/Apache.pm
    version: 1.10
  OpenFrame::Segment::Apache::NoImages:
    file: lib/OpenFrame/Segment/Apache/NoImages.pm
    version: 1.01
  OpenFrame::Segment::Apache::Request:
    file: lib/OpenFrame/Segment/Apache/Request.pm
    version: 1.02
  OpenFrame::Segment::Apache::Response:
    file: lib/OpenFrame/Segment/Apache/Response.pm
    version: 1.02
generated_by: Module::Build version 0.19
